name: NerfNetherPortalZombiePigmen
version: '${project.version}'
main: es.mithrandircraft.nerfnetherportalzombiepigmen.NerfNetherPortalZombiePigmen
api-version: '1.21'
authors: [PixelRain (Mithrandir)]
description: Nerfs drops from nether portal spawned zombie pigmen
